PipelineSecrets:
  DockerConfig: '{"auths":{"jenkinsxcluster.azurecr.io":{"auth":"amVua2luc3hjbHVzdGVyOnJVa01nNj0xRUQ1RmVSZ0h3SERzMEhnL2R0bW0zeW5I"}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 52.151.75.139.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: jenkinsxcluster.azurecr.io
        TILLER_NAMESPACE: kube-system
prow: {}
